---
- hosts: ELK
  remote_user: root
  tasks:
    - name: Install Aptitude package
      apt: update_cache=yes name=aptitude
      tags: [Deploy ELK]

    - name: Upgrade packages
      apt: upgrade=yes
      tags: [Deploy ELK]

    - include_vars: '/home/administrateur/playbooks/elk/defaults/elk_options.yml'
    - include: '{{java_path}}/install_java.yml'
    - include: '{{elk_path}}/elasticsearch/tasks/install_elasticsearch.yml'
    - include: '{{elk_path}}/kibana/tasks/install_kibana.yml'
    - include: '{{elk_path}}/nginx/tasks/install_nginx.yml'
    - include: '{{elk_path}}/logstash/tasks/install_logstash.yml'

    - name: Install packages
      apt:
        name={{item.paquet}}
        update_cache=yes
        state=present
      with_items:
        - { paquet: "rsyslog-gnutls" }
        - { paquet: "gnutls-bin" }
      tags: [ELK]

    - name: Edit Firewall
      command: ufw allow 5014/udp
      tags: [Deploy ELK]

    - name: Edit FW Kibana
      command: ufw allow 5601
      tags: [Deploy ELK]
