---
# This playbook contains common plays that will be run on all nodes

- name: Install UFW
  apt:  name=ufw update_cache=yes state=present

- name: Configure ufw rules
  ufw: rule={{ item.rule }} port={{ item.port }} proto={{ item.proto }}
  with_items:
    - { rule: 'allow', port: '{{ ssh_port | default("22") }}', proto: 'tcp' }
  notify:
    - restart ufw


- name: Configure ufw defaults
  ufw: direction={{ item.direction }} policy={{ item.policy }}
  with_items:
    - { direction: 'incoming', policy: 'deny' }
    - { direction: 'outgoing', policy: 'allow' }
  notify:
    - restart ufw

- name: Enable ufw logging
  ufw: logging=on
  notify:
    - restart ufw # call the handler

- name: Enable ufw
  ufw: state=enabled

- name: Install HTTPS-Transport
  apt:  name=apt-transport-https update_cache=yes state=present

- name: Installing Elasticsearch repo GPG Key
  apt_key: url=https://artifacts.elastic.co/GPG-KEY-elasticsearch state=present

- name: Add ELK repository
  apt_repository: repo="deb https://artifacts.elastic.co/packages/5.x/apt stable main" state=present
