---
- name: Install requiered library
  apt:
    name={{item}}
    state=present
    update_cache=true
  with_items:
    - autoconf 
    - libtool 
    - libprelude-dev

- name: Download barnyard2 
  unarchive: 
    src={{url_install_barnyard2}} 
    dest={{src_install_directory}}
    copy=no

- name: Running ./autogen.sh for barnyard2
  command: ./autogen.sh chdir="{{barnyard2_install_directory}}"

- name: Running ./configure for barnyard2
  command: ./configure CFLAGS="-lpthread" --enable-prelude chdir="{{barnyard2_install_directory}}"

- name: Running make for barnyard2
  command: make chdir="{{barnyard2_install_directory}}"

- name: Running make install for barnyard2
  command: make install chdir="{{barnyard2_install_directory}}"

- name: Copy barnyard2 conf file
  copy:
    src={{barnyard2_install_directory}}/etc/barnyard2.conf
    dest={{snort_path}}
    remote_src=true

- name: Create barnyard2 files
  file: 
     path={{item.name}} 
     state={{item.type}} 
     mode=5775
  with_items:
    - { name: '{{snort_path}}/sid-msg.map', type: 'touch'     }
    - { name: '/var/log/barnyard2',         type: 'directory' }

- name: Configuring barnyard2.conf
  lineinfile:
    dest="{{snort_path}}/barnyard2.conf"
    line={{barnyard2_output}}
    insertafter='#   output alert_prelude{{ ":" }} profile='
