---
# This playbook contains logstash plays that will be run on all nodes
############## INSTALLATION ##############
- name      : Configure ufw rules
  ufw       : rule={{ item.rule }} port={{ item.port }}
  with_items:
    - { rule: 'allow', port: '{{ logstash_listenning_port }}' }
  notify:
    - restart ufw

#- name: super-ugly hack to allow unauthenticated packages to install
#  copy: content='APT::Get::AllowUnauthenticated "true";' dest=/etc/apt/apt.conf.d/99temp owner=root group=root mode=0644
  #https://github.com/ansible/ansible/issues/11620
- name : Installing logstash repo GPG Key
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present

- name: adding repository
  apt_repository: repo="{{logstash_apt_repo_url}}" state=present update_cache=yes #allow_unauthenticated=true


- name: apt install
  apt: name=logstash state=present update_cache=true allow_unauthenticated=true
  ## INSTALLER AVEC DPKG
#- name: remove hack that allows unauthenticated packages to install
#  file: path=/etc/apt/apt.conf.d/99temp state=absent
############## configuration ##############
- name : Pushing logstash Conf files
  copy:
    src: "{{logstash_src_conf_path}}"
    dest: "{{logstash_etc_dir}}"
    owner: "{{ logstash_directory_owner }}"
    group: "{{ logstash_directory_group }}"
    remote_src: False
    mode: 0644

- name: Get file to modify
  find:
    paths: "{{logstash_etc_dir}}/conf.d/"
    patterns: "*.conf"
  register: conf_files


- name: "Replace IP:port in file"
  replace:
    dest="{{item.path}}"
    regexp="var_ELK_elasticsearch_ip:var_ELK_elasticsearch_port"
    replace="{{elasticsearch_ip_addr}}:{{elasticsearch_listenning_port}}"
  with_items: "{{conf_files.files}}"
  notify:
      - validate configuration
      - restart initd
