---
# handle call from common/tasks/main.yml
- name        : restart ufw
  service     : name=ufw state=restarted

- name        : validate configuration
  command     : "{{logstash_start_cmd}} --configtest --config {{logstash_etc_dir}}/conf.d/* "
  changed_when: False
  register    : logstash_configtest
  failed_when : logstash_configtest.rc != 0

- name        : start logstash
  service     : name=logstash state=started enabled=yes
