---
- name: Install required packages
  apt: 
    name={{item}} 
    state=present 
    update_cache=true
  with_items:
    - aptitude
    - build-essential
    - unzip

- name: Upgrade package
  apt: upgrade=yes

- name: Creating install directory
  file: 
     path={{src_install_directory}} 
     state=directory 
     mode=0755
