---

  - name: Check Install OPENSSL
    apt: name=openssl state=present update_cache=true

  - name: Creating Directories
    file:
      path={{item.name}}
      state={{item.type}}
      mode=775
    with_items:
      - {name: '{{dir_pki}}',               type: 'directory'}
      - {name: '{{dir_crl}}',               type: 'directory'}
      - {name: '{{dir_ca}}',                type: 'directory'}
      - {name: '{{dir_certs}}',             type: 'directory'}

      - {name: '{{dir_rootca}}',            type: 'directory'}
      - {name: '{{dir_intca}}',             type: 'directory'}
      - {name: '{{dir_infraca}}',           type: 'directory'}
      - {name: '{{dir_clientca}}',          type: 'directory'}

      - {name: '{{dir_rootca_db}}',         type: 'directory'}
      - {name: '{{dir_intca_db}}',          type: 'directory'}
      - {name: '{{dir_infraca_db}}',        type: 'directory'}
      - {name: '{{dir_clientca_db}}',       type: 'directory'}

      - {name: '{{dir_rootca_certs}}',      type: 'directory'}
      - {name: '{{dir_intca_certs}}',       type: 'directory'}
      - {name: '{{dir_infraca_certs}}',     type: 'directory'}
      - {name: '{{dir_clientca_certs}}',    type: 'directory'}

      - {name: '{{file_rootca_crt}}',       type: 'touch'}
      - {name: '{{file_rootca_db}}',        type: 'touch'}
      - {name: '{{file_rootca_dbattr}}',    type: 'touch'}
      - {name: '{{file_rootca_crl}}',       type: 'touch'}

      - {name: '{{file_intca_crt}}',        type: 'touch'}
      - {name: '{{file_intca_db}}',         type: 'touch'}
      - {name: '{{file_intca_dbattr}}',     type: 'touch'}
      - {name: '{{file_intca_crl}}',        type: 'touch'}

      - {name: '{{file_infraca_crt}}',      type: 'touch'}
      - {name: '{{file_infraca_db}}',       type: 'touch'}
      - {name: '{{file_infraca_dbattr}}',   type: 'touch'}
      - {name: '{{file_infraca_crl}}',      type: 'touch'}

      - {name: '{{file_clientca_crt}}',     type: 'touch'}
      - {name: '{{file_clientca_db}}',      type: 'touch'}
      - {name: '{{file_clientca_dbattr}}',  type: 'touch'}
      - {name: '{{file_clientca_crl}}',     type: 'touch'}

  - name: Creating Private Directories
    file:
      path={{item.name}}
      state={{item.type}}
      mode=700
    with_items:
      - {name: '{{dir_rootca_priv}}',       type: 'directory'}
      - {name: '{{dir_intca_priv}}',        type: 'directory'}
      - {name: '{{dir_infraca_priv}}',      type: 'directory'}
      - {name: '{{dir_clientca_priv}}',     type: 'directory'}

  - name: Adding values
    lineinfile:
      dest={{item.name}}
      line={{item.value}}
    with_items:
      - {name: '{{file_rootca_crt}}',   value: '01'}
      - {name: '{{file_rootca_crl}}',   value: '01'}
      - {name: '{{file_intca_crt}}',    value: '01'}
      - {name: '{{file_intca_crl}}',    value: '01'}
      - {name: '{{file_infraca_crt}}',  value: '01'}
      - {name: '{{file_infraca_crl}}',  value: '01'}
      - {name: '{{file_clientca_crt}}', value: '01'}
      - {name: '{{file_clientca_crl}}', value: '01'}

  - name : Pushing Conf files
    copy:
      src: "roles/pki/conf"
      dest: "{{dir_pki}}"
      remote_src: False
      mode: 0644

  - name: Get file to modify
    find:
      paths: "{{dir_conf}}"
      patterns: "*.conf"
    register: conf_files

  - name: "Replace in file"
    replace:
      dest="{{item.path}}"
      regexp="PATH_TO_MAIN_CA_FOLDER"
      replace="{{dir_ca}}"
    with_items: "{{conf_files.files}}"




  - name: "{{name_rootca}} Generate Key"
    command: "openssl req -new -config {{conf_rootca}} -nodes -out {{dir_rootca}}/{{name_rootca}}.csr -keyout {{dir_rootca_priv}}/{{name_rootca}}.key"

  - name: "{{name_rootca}} Sign Cert"
    command: "openssl ca -selfsign -batch -config {{conf_rootca}} -in {{dir_rootca}}/{{name_rootca}}.csr -out {{dir_rootca}}/{{name_rootca}}.crt -extensions root_ca_ext"

  - name: "{{name_rootca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_rootca}} -out {{dir_crl}}/{{name_rootca}}.crl"



  - name: "{{name_intca}} Generate Key"
    command: "openssl req -new -config {{conf_intca}} -nodes -out {{dir_intca}}/{{name_intca}}.csr -keyout {{dir_intca_priv}}/{{name_intca}}.key"

  - name: "{{name_intca}} Sign Cert"
    command: "openssl ca -batch -config {{conf_rootca}} -in {{dir_intca}}/{{name_intca}}.csr -out {{dir_intca}}/{{name_intca}}.crt -extensions intermediate_ca_ext"

  - name: "{{name_intca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_intca}} -out {{dir_crl}}/{{name_intca}}.crl"



  - name: "{{name_infraca}} Generate Key"
    command: "openssl req -new -config {{conf_infraca}} -nodes -out {{dir_infraca}}/{{name_infraca}}.csr -keyout {{dir_infraca_priv}}/{{name_infraca}}.key"

  - name: "{{name_infraca}} Sign Cert"
    command: "openssl ca -batch -config {{conf_intca}} -in {{dir_infraca}}/{{name_infraca}}.csr -out {{dir_infraca}}/{{name_infraca}}.crt -extensions signing_ca_ext"

  - name: "{{name_infraca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_infraca}} -out {{dir_crl}}/{{name_infraca}}.crl"



  - name: "{{name_clientca}} Generate Key"
    command: "openssl req -new -config {{conf_clientca}} -nodes -out {{dir_clientca}}/{{name_clientca}}.csr -keyout {{dir_clientca_priv}}/{{name_clientca}}.key"

  - name: "{{name_clientca}} Sign Cert"
    command: "openssl ca -batch -config {{conf_intca}} -in {{dir_clientca}}/{{name_clientca}}.csr -out {{dir_clientca}}/{{name_clientca}}.crt -extensions signing_ca_ext"

  - name: "{{name_clientca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_clientca}} -out {{dir_crl}}/{{name_clientca}}.crl"



  - name: "Chained Certs Int-CA"
    shell: cat {{dir_intca}}/{{name_intca}}.crt {{dir_rootca}}/{{name_rootca}}.crt > {{dir_certs}}/int-ca-chain.pem

  - name: "Chained Certs Infra-Int-CA"
    shell: cat {{dir_infraca}}/{{name_infraca}}.crt {{dir_certs}}/int-ca-chain.pem > {{dir_certs}}/infra-int-ca-chain.pem

  - name: "Chained Certs Client-Int-CA"
    shell: cat {{dir_clientca}}/{{name_clientca}}.crt {{dir_certs}}/int-ca-chain.pem > {{dir_certs}}/client-int-ca-chain.pem
