---

  - name: Check Install OPENSSL
    apt: name=openssl state=present update_cache=true

  - name: Creating Offline CA Directories
    file:
      path={{item.name}}
      state={{item.type}}
      mode=775
    with_items:
      - {name: '{{dir_pki}}',               type: 'directory'}
      - {name: '{{dir_crl}}',               type: 'directory'}
      - {name: '{{dir_ca}}',                type: 'directory'}
      - {name: '{{dir_certs}}',             type: 'directory'}
      - {name: '{{dir_conf}}',             type: 'directory'}

      - {name: '{{dir_rootca}}',            type: 'directory'}
      - {name: '{{dir_intca}}',             type: 'directory'}

      - {name: '{{dir_rootca_db}}',         type: 'directory'}
      - {name: '{{dir_intca_db}}',          type: 'directory'}

      - {name: '{{dir_rootca_certs}}',      type: 'directory'}
      - {name: '{{dir_intca_certs}}',       type: 'directory'}

      - {name: '{{file_rootca_crt}}',       type: 'touch'}
      - {name: '{{file_rootca_db}}',        type: 'touch'}
      - {name: '{{file_rootca_dbattr}}',    type: 'touch'}
      - {name: '{{file_rootca_crl}}',       type: 'touch'}

      - {name: '{{file_intca_crt}}',        type: 'touch'}
      - {name: '{{file_intca_db}}',         type: 'touch'}
      - {name: '{{file_intca_dbattr}}',     type: 'touch'}
      - {name: '{{file_intca_crl}}',        type: 'touch'}

  - name: Creating Offline Private Directories
    file:
      path={{item.name}}
      state=directory
      mode=700
    with_items:
      - {name: '{{dir_rootca_priv}}'}
      - {name: '{{dir_intca_priv}}'}

  - name: Adding values to Offline Files
    lineinfile:
      dest={{item.name}}
      line="01"
    with_items:
      - {name: '{{file_rootca_crt}}'}
      - {name: '{{file_rootca_crl}}'}
      - {name: '{{file_intca_crt}}'}
      - {name: '{{file_intca_crl}}'}

  - name: Creating Online CA Directories
    file:
      path="{{dir_ca}}/{{item.name}}"
      state=directory
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Directories DB
    file:
      path="{{dir_ca}}/{{item.name}}/db"
      state=directory
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Directories CERTS
    file:
      path="{{dir_ca}}/{{item.name}}/certs"
      state=directory
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Directories PRIV
    file:
      path="{{dir_ca}}/{{item.name}}/private"
      state=directory
      mode=700
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Files CRT
    file:
      path="{{dir_ca}}/{{item.name}}/db/{{item.name}}.crt.srl"
      state=touch
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Files CRL
    file:
      path="{{dir_ca}}/{{item.name}}/db/{{item.name}}.crl.srl"
      state=touch
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Files DB
    file:
      path="{{dir_ca}}/{{item.name}}/db/{{item.name}}.db"
      state=touch
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Creating Online CA Files DB ATTR
    file:
      path="{{dir_ca}}/{{item.name}}/db/{{item.name}}.db.attr"
      state=touch
      mode=775
    with_items: "{{ Added_CA_List }}"

  - name: Adding values to Online Files CRT
    lineinfile:
      dest="{{dir_ca}}/{{item.name}}/db/{{item.name}}.crt.srl"
      line="01"
    with_items: "{{ Added_CA_List }}"

  - name: Adding values to Online Files CRL
    lineinfile:
      dest="{{dir_ca}}/{{item.name}}/db/{{item.name}}.crl.srl"
      line="01"
    with_items: "{{ Added_CA_List }}"

  - name : Creating Offline CA Conf Root
    copy:
      src: "roles/pki/conf/RootCA.conf"
      dest: "{{dir_conf}}/RootCA.conf"
      remote_src: False
      mode: 0644

  - name : Creating Offline CA Conf Int
    copy:
      src: "roles/pki/conf/IntCA.conf"
      dest: "{{dir_conf}}/IntCA.conf"
      remote_src: False
      mode: 0644

  - name : Creating Offline CA Conf Client
    copy:
      src: "roles/pki/conf/Client.conf"
      dest: "{{dir_conf}}/Client.conf"
      remote_src: False
      mode: 0644

  - name : Creating Online CA Conf files
    copy:
      src: "roles/pki/conf/default.conf"
      dest: "{{dir_conf}}/{{item.name}}.conf"
      remote_src: False
      mode: 0644
    with_items: "{{ Added_CA_List }}"


  - name: Get file to modify
    find:
      paths: "{{dir_conf}}"
      patterns: "*.conf"
    register: conf_files

  - name: "Replace in file"
    replace:
      dest="{{item.path}}"
      regexp="PATH_TO_MAIN_CA_FOLDER"
      replace="{{dir_ca}}"
    with_items: "{{conf_files.files}}"

  - name: "Replace in file part 2"
    replace:
      dest="{{dir_conf}}/{{item.name}}.conf"
      regexp="CA_NAME"
      replace="{{item.name}}"
    with_items: "{{ Added_CA_List }}"




  - name: "{{name_rootca}} Generate Key"
    command: "openssl req -new -config {{conf_rootca}} -nodes -out {{dir_rootca}}/{{name_rootca}}.csr -keyout {{dir_rootca_priv}}/{{name_rootca}}.key"

  - name: "{{name_rootca}} Sign Cert"
    command: "openssl ca -selfsign -batch -config {{conf_rootca}} -in {{dir_rootca}}/{{name_rootca}}.csr -out {{dir_rootca}}/{{name_rootca}}.crt -extensions root_ca_ext"

  - name: "{{name_rootca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_rootca}} -out {{dir_crl}}/{{name_rootca}}.crl"



  - name: "{{name_intca}} Generate Key"
    command: "openssl req -new -config {{conf_intca}} -nodes -out {{dir_intca}}/{{name_intca}}.csr -keyout {{dir_intca_priv}}/{{name_intca}}.key"

  - name: "{{name_intca}} Sign Cert"
    command: "openssl ca -batch -config {{conf_rootca}} -in {{dir_intca}}/{{name_intca}}.csr -out {{dir_intca}}/{{name_intca}}.crt -extensions intermediate_ca_ext"

  - name: "{{name_intca}} Generate CRL"
    command: "openssl ca -gencrl -config {{conf_intca}} -out {{dir_crl}}/{{name_intca}}.crl"


  - name: Generate Offline CA Priv Keys
    command: "openssl req -new -config {{dir_conf}}/{{item.name}}.conf -nodes -out {{dir_ca}}/{{item.name}}/{{item.name}}.csr -keyout {{dir_ca}}/{{item.name}}/private/{{item.name}}.key"
    with_items: "{{ Added_CA_List }}"

  - name: Signing Offline CA Certs
    command: "openssl ca -batch -config {{conf_intca}} -in {{dir_ca}}/{{item.name}}/{{item.name}}.csr -out {{dir_ca}}/{{item.name}}/{{item.name}}.crt -extensions signing_ca_ext"
    with_items: "{{ Added_CA_List }}"

  - name: Generate Offline CA CRL
    command: "openssl ca -gencrl -config {{dir_conf}}/{{item.name}}.conf -out {{dir_crl}}/{{item.name}}.crl"
    with_items: "{{ Added_CA_List }}"

  - name: "Chained Certs Int-CA"
    shell: cat {{dir_intca}}/{{name_intca}}.crt {{dir_rootca}}/{{name_rootca}}.crt > {{dir_certs}}/int-ca-chain.pem

  - name: Chained Online CA Certs
    shell: cat {{dir_ca}}/{{item.name}}/{{item.name}}.crt {{dir_certs}}/int-ca-chain.pem > {{dir_certs}}/{{item.name}}-int-ca-chain.pem
    with_items: "{{ Added_CA_List }}"
